config/routes.rb
Takenote::Application.routes.draw do
  
  get "users/login"

  get "users/logout"

  get "sessions/new"

  get "sessions/destroy"

  match 'notes/search' => "notes#search", :via => :get, :as => "search"
  match 'notes/search' => "notes#result", :via => :post

  resources :notes

  resources :courses

  resources :users
  
  resources :session
  
  match '/login' => "sessions#create", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/signup' => "users#new", :as => "signup"
  

  

  match 'users/:id' => 'users#show'

  root :to => "sessions#create"

  match ':controller/:action/:id',
            :controller => "user",
            :action => "show"
  match '/courses/destroy/:id' => 'courses#destroy', :as => 'destroy_course'
  match '/users/destroy/:id' => 'users#destroy', :as => 'destroy_user'
  match '/users/show/:id' => 'users#show', :as => 'show_user'
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :course
  validates :course_id, :presence => true
  validates :date, :presence => true
  validates :title, :presence => true
  default_scope order('notes.course_id')
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  layout 'users'
  before_filter :authorize

  # GET /notes/1
  # GET /notes/1.xml
  def show
    @user = current_user
    @courses = Course.find(:all, :conditions => ["user_id = ?", @user.id])
    @notes = Note.find(:all, :conditions => ["course_id = ?", params[:id]], :order => "date")
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.xml
  def new
    @user = current_user
    @courses = @user.course
    @note = Note.new
    @course = params[:course]
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @note ; @course ; @user }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
    @user = current_user
    @courses = Course.find(:all, :conditions => ["user_id = ?", @user.id])
  end

  # POST /notes
  # POST /notes.xml
  def create
    @note = Note.new(params[:note])
    @course = Course.find(@note.course_id)
    @course.number = @course.number + 1
    @course.save
    @user = current_user
    @courses = Course.find(:all, :conditions => ["user_id = ?", @user.id])
    respond_to do |format|
      if @note.save
        format.html { redirect_to :controller => "courses", :action => "show", :id => @note.course_id }
        format.xml  { render :xml => @note, :status => :created, :location => @note }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.xml
  def update
    @note = Note.find(params[:id])
    @user = current_user
    @courses = Course.find(:all, :conditions => ["user_id = ?", @user.id])
    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to :controller => "notes", :action => "edit", :id => @note.id, :notice => 'Note was successfully updated.' }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.xml
  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    @course = Course.find(@note.course_id)
    @course.number = @course.number - 1
    @course.save

    respond_to do |format|
      format.html { redirect_to(user_url) }
      format.xml  { head :ok }
    end
  end
  
  def search
    @user = current_user
    @courses = Course.find(:all, :conditions => ["user_id = ?", @user.id])
    @course_select_list = [['All', 0]] + Course.find(:all, :conditions => ["user_id = ?", @user.id]).collect { |x| [x.name, x.id] }
  end
  
  def result
    @user = current_user
    @courses = Course.find(:all, :conditions => ["user_id = ?", @user.id])
    f = params[:course_spec].to_i
    yfrom = params[:date]["from(1i)"].to_i
    mfrom = params[:date]["from(2i)"].to_i
    dfrom = params[:date]["from(3i)"].to_i
    yto = params[:date]["to(1i)"].to_i
    mto = params[:date]["to(2i)"].to_i
    dto = params[:date]["to(3i)"].to_i
    key = params[:key]
    query ="%"
    query << key 
    query << "%"
    if f == 0
      @notes = Note.where "user_id = ? AND date BETWEEN '?-?-?' AND '?-?-?' AND (content like ? OR title like ?)", @user.id, yfrom, mfrom, dfrom, yto, mto, dto, query, query
    else
      @notes = Note.where "user_id = ? AND course_id = ? AND date BETWEEN '?-?-?' AND '?-?-?' AND (content like ? OR title like ?)", @user.id, f, yfrom, mfrom, dfrom, yto, mto, dto, query, query
    end
    flash.now[:notice] = "Searh result"
    render 'show'
  end
  
  protected
  def authorize
    unless User.find_by_id(session[:user_id])
      flash[:notice] = "Please log in"
      redirect_to :controller => :sessions, :action => :create
    end
  end


end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/edit.html.erb
<h1><center>Editing note</center></h1>

<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :course %>:
	<% @course = Course.find(@note.course_id) %> 
    <%= @course.name %>

  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :size => "80x20" %>
  </div>
  <div class="actions">
  	<%= f.hidden_field :user_id, :value => @user.id %>
	<%= f.submit "Update", :class => "submit" %>
	<%= link_to 'Back to list', show_user_path(@user) %>
  </div>
<% end %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :course %>:
	<% @c = Course.find(@course) %> 
    <%= @c.name %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :size => "80x20" %>
  </div>
  <div class="actions">
  	<%= f.hidden_field :user_id, :value => @user.id %>
	<%= f.hidden_field :course_id, :value => @course %>
    <%= submit_or_cancel(f) %>
  </div>
<% end %>

app/views/notes/search.html.erb
<% if flash[:notice] %>
	<%= flash[:notice] %>
<% end %>
<h1><center>Search note</center></h1>

<%= form_tag do %>

Course<br>
<%= select_tag :course_spec, options_for_select(@course_select_list) %>
<br/>
Written time<br>
From<br>
<%= date_select("date", "from", :default => { :year => 2009 }) %><br>
To<br>
<%= date_select("date", "to") %><br>
Keyword<br>
<%= text_field_tag 'key', '' %>

<br><br><br>
<center><%= submit_tag 'Search' %></center>
<% end %>


app/views/notes/show.html.erb
<% @notes.each do |note| %>
	<h2><center><%= note.title %></center></h2>
		<p align=right><strong>Date: </strong><%= note.date %><strong> Course: </strong>
		<% @course = Course.find(note.course_id)%>
		<%=@course.name  %></p>
		<p><%= note.content %></p>
		<td><%= link_to 'Edit', edit_note_path(note) %></td>
    	<td><%= link_to 'Destroy', note, :confirm => 'Are you sure?', :method => :delete %></td>
<% end %>