config/routes.rb
Takenote::Application.routes.draw do
  
  get "users/login"

  get "users/logout"

  get "sessions/new"

  get "sessions/destroy"

  match 'notes/search' => "notes#search", :via => :get, :as => "search"
  match 'notes/search' => "notes#result", :via => :post

  resources :notes

  resources :courses

  resources :users
  
  resources :session
  
  match '/login' => "sessions#create", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/signup' => "users#new", :as => "signup"
  

  

  match 'users/:id' => 'users#show'

  root :to => "sessions#create"

  match ':controller/:action/:id',
            :controller => "user",
            :action => "show"
  match '/courses/destroy/:id' => 'courses#destroy', :as => 'destroy_course'
  match '/users/destroy/:id' => 'users#destroy', :as => 'destroy_user'
  match '/users/show/:id' => 'users#show', :as => 'show_user'
end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
	
  attr_accessor :password
  has_many :course
	has_many :notes, :through => :course, :source => :note
	
	validates_presence_of :acc, :password, :name, :mail
	validates_uniqueness_of :acc
	
  validates :mail, :uniqueness => true,
                   :length => { :within => 5..50 },
                   :format => { :with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i }
	
  validates :password, :confirmation => true, 
                       :length => {:within => 6..30},
                       :presence => true,
                       :if => :password_required?
	
	
	before_save :encrypt_new_password

  def self.authenticate(acc, password)
    user = find_by_acc(acc)
    return user if user && user.authenticated?(password)
  end

  def authenticated?(password)
    self.hashed_password == encrypt(password)
  end

  protected
    def encrypt_new_password
      return if password.blank?
      self.hashed_password = encrypt(password)
    end

    def password_required?
      hashed_password.blank? || password.present?
    end

    def encrypt(string)
      Digest::SHA1.hexdigest(string)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	before_filter :authorize, :except => [:new, :create]
  


  # GET /users/1
  # GET /users/1.xml
  def show
    @user = current_user
    @courses = Course.find(:all, :conditions => ["user_id = ?", @user.id])
	  @notes = Note.find(:all, :conditions => ["user_id = ?", @user.id], :order => "date DESC")
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user ; @courses ; @notes }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html { render :layout => 'sessions'}
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = current_user
    @courses = Course.find(:all, :conditions => ["user_id = ?", @user.id])
  end
  

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])
    
    respond_to do |format|
      if @user.save
      	flash[:notice] = "User #{@user.acc} was successfully created."
        format.html { redirect_to(login_path, :notice => 'User was successfully created. Please login!') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = current_user
    @courses = Course.find(:all, :conditions => ["user_id = ?", @user.id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
      	flash[:notice] = "User #{@user.acc} was successfully updated."
        format.html { redirect_to(@user, :notice => 'User information was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = current_user
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(login_path) }
      format.xml  { head :ok }
    end
  end
  
  protected
  def authorize
  	unless User.find_by_id(session[:user_id])
  		flash[:notice] = "Please log in"
  		redirect_to :controller => :sessions, :action => :create
  	end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :account %><br />
    <%= f.text_field :acc, :size => 40 %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, :size => 40 %>
  </div>
  
  <div class="field">
    <%= f.label :confirm %><br />
    <%= f.password_field :password_confirmation, :size => 40 %>
  </div>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :size => 40 %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :mail, :size => 40 %>
  </div>
    <%= f.submit "Sign up", :class => "submit" %>
<% end %>

app/views/users/edit.html.erb
<h1><center>Editing user</center></h1>
<br>
<br>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table>
  <tr><div class="field">
    <td><%= f.label :account %></td> 
    <td><%= @user.acc %></td>
  </div>
  </tr>
  <tr>
  <div class="field">
    <td><%= f.label :name %><br /></td>
    <td><%= f.text_field :name, :size => 40 %></td>
  </div>
  </tr>
  <tr>
  <div class="field">
    <td><%= f.label :email %><br /></td>
    <td><%= f.text_field :mail, :size => 40 %></td>
  </div>
  </tr>
  <div class="field">
    <td><%= f.label :Password %><br /></td>
    <td><%= f.password_field :password, :size => 40 %></td>
  </div>
  </tr>
  <tr>
  <div class="field">
    <td><%= f.label :Confirmation %><br /></td>
    <td><%= f.password_field :password_confirmation, :size => 40 %></td>
  </div>	
</table>
<br><br>
<center><%= submit_or_cancel(f) %></center>
<br><br>
If you don't want to use this service anymore. Click <%= link_to 'here', destroy_user_path, :confirm => 'Are you sure?', :method => :delete %> to destroy your account!
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1> 
<h2>It's free, and always will be.</h2>

<%= render 'form' %>

<%= link_to 'Back', login_path %>

app/views/users/show.html.erb
<% if flash[:notice] %>
	<%= flash[:notice] %>
<% end %>
<% @notes.each do |note| %>
	<h2><center><%= note.title %></center></h2>
		<p align=right><strong>Date: </strong><%= note.date %><strong> Course: </strong>
		<% @course = Course.find(note.course_id)%>
		<%=@course.name  %></p>
		<p><%= note.content %></p>
		<td><%= link_to 'Edit', edit_note_path(note) %></td>
    	<td><%= link_to 'Destroy', note, :confirm => 'Are you sure?', :method => :delete %></td>
<% end %>
					
					