config/routes.rb
Takenote::Application.routes.draw do
  
  get "users/login"

  get "users/logout"

  get "sessions/new"

  get "sessions/destroy"

  match 'notes/search' => "notes#search", :via => :get, :as => "search"
  match 'notes/search' => "notes#result", :via => :post

  resources :notes

  resources :courses

  resources :users
  
  resources :session
  
  match '/login' => "sessions#create", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/signup' => "users#new", :as => "signup"
  

  

  match 'users/:id' => 'users#show'

  root :to => "sessions#create"

  match ':controller/:action/:id',
            :controller => "user",
            :action => "show"
  match '/courses/destroy/:id' => 'courses#destroy', :as => 'destroy_course'
  match '/users/destroy/:id' => 'users#destroy', :as => 'destroy_user'
  match '/users/show/:id' => 'users#show', :as => 'show_user'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  
  # GET /courses/1
  # GET /courses/1.xml
  
  before_filter :authorize
  def show
    @user = current_user
    @courses = Course.find(:all, :conditions => ["user_id = ?", @user.id])
    @course = current_user.course.find(params[:id])
    @notes = Note.find(:all, :conditions => ["course_id = ?", params[:id]], :order => "date DESC")

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @course ; @notes }
    end
  end

  # GET /courses/new
  # GET /courses/new.xml
  def new
    
    @user = current_user
    @courses = Course.find(:all, :conditions => ["user_id = ?", @user.id])
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @user = current_user
    @courses = Course.find(:all, :conditions => ["user_id = ?", @user.id])
    @course = current_user.course.find(params[:id])
  end
  

  # POST /courses
  # POST /courses.xml
  def create
    @user = current_user
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to(@course, :notice => 'Course was successfully created.') }
        format.xml  { render :xml => @course, :status => :created, :location => @course }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.xml
  def update
    @user = current_user
    @course = current_user.course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to(@course, :notice => 'Course was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.xml
  def destroy
    @user = current_user
    @course = current_user.course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to(@user) }
      format.xml  { head :ok }
    end
  end
  
  protected
  def authorize
    unless User.find_by_id(session[:user_id])
      flash[:notice] = "Please log in"
      redirect_to :controller => :sessions, :action => :create
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <br><br>
  <div class="actions">
    <%= f.hidden_field :user_id, :value => session[:user_id]%>
    <%= submit_or_cancel(f) %>
  </div>
<% end %>

app/views/courses/new.html.erb
<h1><center>Create new course</center></h1>

<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <br><br>
  <div class="actions">
    <%= f.hidden_field :user_id, :value => session[:user_id]%>
	<%= f.hidden_field :number, :value => 0 %>
    <%= submit_or_cancel(f) %>
  </div>
<% end %>

app/views/courses/show.html.erb
<% if flash[:notice] %>
	<%= flash[:notice] %>
<% end %>
<h1><center><%= @course.name %></center></h1>
<h3><center>-- <%= @course.comment %> -- </center></h3>
<%= token_tag %> 
<p align="right">
<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Delete', destroy_course_path, :confirm => 'Are you sure?', :method => :delete %>
</p>
<p id="notice"><%= notice %></p>
<%= link_to 'Create new note', new_note_path(:course => @course)  %>

<% @notes.each do |note| %>
	<h2><center><%= note.title %></center></h2>
		<p align=center><strong>Date: </strong><%= note.date %><strong> Course: </strong>
		<% @course = Course.find(note.course_id)%>
		<%=@course.name  %></p>
		<p><%= note.content %></p>
		<td><%= link_to 'Edit', edit_note_path(note) %></td>
    	<td><%= link_to 'Destroy', note, :confirm => 'Are you sure?', :method => :delete %></td>
<% end %>

<br />