config/routes.rb
Takenote::Application.routes.draw do
  
  get "users/login"

  get "users/logout"

  get "sessions/new"

  get "sessions/destroy"

  match 'notes/search' => "notes#search", :via => :get, :as => "search"
  match 'notes/search' => "notes#result", :via => :post

  resources :notes

  resources :courses

  resources :users
  
  resources :session
  
  match '/login' => "sessions#create", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/signup' => "users#new", :as => "signup"
  

  

  match 'users/:id' => 'users#show'

  root :to => "sessions#create"

  match ':controller/:action/:id',
            :controller => "user",
            :action => "show"
  match '/courses/destroy/:id' => 'courses#destroy', :as => 'destroy_course'
  match '/users/destroy/:id' => 'users#destroy', :as => 'destroy_user'
  match '/users/show/:id' => 'users#show', :as => 'show_user'
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" >
<html>
	<head>
		<title>Web Note - a new way to take note in class</title>
		<%= stylesheet_link_tag "webnote" , :media => "all" %>
		<%= javascript_include_tag :defaults %>
		
	</head>
	<body>
		<div id="container">
			<div id="company"><img src="images/webnotehappy-header.png" alt="Webnote - a better bookmark manager for your Mac - Surf. Write. Remember."></div>
			<div id="navbar">
			<ul>
				<li id="currentpage"><a href="#">Home</a></li>
				<li><a href="#">About</a></li>
				<li><a href="#">FAQ</a></li>
				<li><a href="#">Contact</a></li>
				<li><%= link_to 'Sign in/Sign up', login_path %></li>
			</ul>
		</div>
		<%= yield %>
		<div id="footer">© 2010 Web Note - Created by Doan Hoai Nam - Keio University.</div>
	   </div>
	</body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" >
<html>
	<head>
		<title>Web Note - a new way to take note in class</title>
		<%= stylesheet_link_tag "webnote" , :media => "all" %>
		<%= javascript_include_tag :defaults %>
		
	</head>
	<body>
		<div id="container">
			<div id="company">
				<%= image_tag("webnote-header.png") %>

			</div>
			
			<div id="content"> 
				<%= yield :layout %>
			</div>
			<div id="sidebar">
           		<ul>
               		<li><div class="banana"><a href="">Webnote Application 2.0</a></div>
               		<ul>
                 	<li></li>
                 	<li></li>
                 	<li>Now you can use Web Note in your device:</li>
                 	<li>Smart phone: iPhone, Android</li>
                 	<li>Windows: 7, XP</li>
                 	<li>Mac OS X 10.4 or later</li>
                 	<li>Snow Leopard compatible</li>
        			<li><b>Automatic synchronous</b></li>
					</ul>
            		</li>
				</ul>
                       
	         <ul>
               <li><div class="banana"><a href="">Contact us</a></div>
				<ul>
						<li>Tell me how you think about Web Note</li>
						<li>Help me to improve features</li>
						<li>Please mail to: perry@sfc.wide.ad.jp</li>
					</ul>
					</li>
            </ul>
            

            
		</div>
		<div id="footer">© 2010 Web Note - Created by Doan Hoai Nam - Keio University.</div>
	   </div>
	</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" >
<html>
	<head>
		<title>Web Note - a new way to take note in class</title>
		<%= stylesheet_link_tag "webnote" , :media => "all" %>
		<%= javascript_include_tag :defaults %>
		
	</head>
	<body>
		<div id="container">
			<div id="company">
				<%= image_tag("webnote-header.png") %>
			</div>
			
			<div id="content">
		
				<%= yield :layout %>           
        	</div>    
        	<div id="sidebar">
        	<ul>
            	<li><div class="banana"><%= link_to 'Account Information', user_path(@user) %></div>
					
				<ul>
  					<li><strong>Account: </strong><%= @user.acc %></li>
  					<li><strong>Full name: </strong><%= @user.name %></li>
  					<li><strong>E-mail: </strong><%= @user.mail %></li>
					<li>
						<%= link_to 'Edit Information', edit_user_path(@user) %> |
						<%= link_to 'Log out', logout_path %>
					</li>
				</ul>
			</ul>
			<ul>
				<li><div class="banana"><%= link_to 'List Course', user_path(@user) %></div>
				<ul>
					<table>
					<% @courses.each do |course| %>
					<% @title = course.name + ' (' + course.number.to_s + ')' %>
					<tr>
						<td><strong><%= link_to @title, course %></strong></td>
	    				<td><%= link_to 'Edit', edit_course_path(course) %></td>
	   					<td><%= link_to 'Destroy', course, :confirm => 'Are you sure?', :method => :delete %></td>
					</tr>
					<% end %>
					</table>
					<li>
						<%= link_to 'New Course', new_course_path %>
					</li>
					
				</ul>
				</li>	
			</ul>	
			
			<ul>
				<li><div class="banana"><%= link_to 'Search note', search_path(@user) %></div>
				</li>	
			</ul>

		</div>
		<br />


	</div>
	<div id="footer">© 2010 Web Note - Created by Doan Hoai Nam - Keio University.</div>
	</div>
	</body>
</html>